// <auto-generated />
using System;
using JHSArena.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JHSArena.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(JHSArenaDbContext))]
    partial class JHSArenaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JHSArena.Domain.Entities.Espaco", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTimeOffset?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<Guid?>("AtualizadoPor")
                        .HasColumnType("uuid")
                        .HasColumnName("atualizado_por");

                    b.Property<int>("Capacidade")
                        .HasColumnType("integer")
                        .HasColumnName("capacidade");

                    b.Property<string>("CorAgenda")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("cor_agenda");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<Guid?>("CriadoPor")
                        .HasColumnType("uuid")
                        .HasColumnName("criado_por");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descricao");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<TimeOnly>("HorarioAbertura")
                        .HasColumnType("time without time zone")
                        .HasColumnName("horario_abertura");

                    b.Property<TimeOnly>("HorarioFechamento")
                        .HasColumnType("time without time zone")
                        .HasColumnName("horario_fechamento");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nome");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("observacoes");

                    b.Property<bool>("PermiteAula")
                        .HasColumnType("boolean")
                        .HasColumnName("permite_aula");

                    b.Property<bool>("PermiteDayUse")
                        .HasColumnType("boolean")
                        .HasColumnName("permite_day_use");

                    b.Property<bool>("PermiteRanking")
                        .HasColumnType("boolean")
                        .HasColumnName("permite_ranking");

                    b.Property<bool>("PermiteReservaOnline")
                        .HasColumnType("boolean")
                        .HasColumnName("permite_reserva_online");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("TempoMinimoReservaMinutos")
                        .HasColumnType("integer")
                        .HasColumnName("tempo_minimo_reserva_minutos");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.Property<Guid>("UnidadeId")
                        .HasColumnType("uuid")
                        .HasColumnName("unidade_id");

                    b.Property<decimal>("ValorHora")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("valor_hora");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "Status")
                        .HasDatabaseName("ix_espacos_empresa_status");

                    b.HasIndex("EmpresaId", "UnidadeId", "Nome")
                        .IsUnique()
                        .HasDatabaseName("ux_espacos_empresa_unidade_nome");

                    b.ToTable("espacos", (string)null);
                });

            modelBuilder.Entity("JHSArena.Domain.Entities.ItemAgenda", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTimeOffset?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<Guid?>("AtualizadoPor")
                        .HasColumnType("uuid")
                        .HasColumnName("atualizado_por");

                    b.Property<DateTimeOffset?>("CanceladoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelado_em");

                    b.Property<Guid?>("CanceladoPor")
                        .HasColumnType("uuid")
                        .HasColumnName("cancelado_por");

                    b.Property<Guid?>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<Guid?>("CriadoPor")
                        .HasColumnType("uuid")
                        .HasColumnName("criado_por");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("descricao");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<Guid>("EspacoId")
                        .HasColumnType("uuid")
                        .HasColumnName("espaco_id");

                    b.Property<DateTimeOffset>("Fim")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fim");

                    b.Property<DateTimeOffset>("Inicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("inicio");

                    b.Property<string>("MotivoCancelamento")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("motivo_cancelamento");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("titulo");

                    b.Property<Guid>("UnidadeId")
                        .HasColumnType("uuid")
                        .HasColumnName("unidade_id");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "Status")
                        .HasDatabaseName("ix_itens_agenda_empresa_status");

                    b.HasIndex("EmpresaId", "UnidadeId", "Inicio")
                        .HasDatabaseName("ix_itens_agenda_empresa_unidade_inicio");

                    b.HasIndex("EmpresaId", "EspacoId", "Inicio", "Fim")
                        .HasDatabaseName("ix_itens_agenda_empresa_espaco_periodo");

                    b.ToTable("itens_agenda", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
